# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e235d90ffa80778abc505ad1d4d446f38235fb7ae6ea3ace2ca6e988faaff488751baf334048d37c9694ace4118f834a15fbb7a59b339117cfeed809a0d1b4a

test:
  secret_key_base: 857cd95ed43d927b40cc94b811979767f20a0d55977e5bdf612d7bbb27b22680820005ed37e9756c192141faf3a9bc76a84d52a036db5fc8714298713fdaf9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
